/*Exemplo de rota*/
app.config(function($routeProvider){
	$routeProvider.when('/',{
		templateUrl:'view/home.html',
		controller:'homeController'
	}).when('/homeUsuario',{
		templateUrl:'view/homeUsuario.html',
		controller:'homeUsuarioController'
	}).when('/usuario/cadastrar-usuario',{
		templateUrl:'view/cadastro.html',
		controller:'cadastroController'
	}).when('/usuario/alterar-usuario',{
		templateUrl:'view/alterarUsuario.html',
		controller:'alterarUsuarioController'
	}).when('/redefinirSenhaIdentificarUsuario',{
		templateUrl:'../view/redefinirSenhaIdentificarUsuario.html',
		controller:'redefinirSenhaController'
	}).when('/redefinirSenha/:token',{
		templateUrl:'../view/redefinirSenha.html',
		controller:'redefinirSenhaController'
	}).when('/login',{
		templateUrl:'view/login.html',
		controller:'loginController'
	}).when('/anuncio/criar-anuncio',{
		templateUrl:'view/criarAnuncio/criarAnuncio.html',
		controller:'anuncioController'
	}).when('/anuncio/veiculo/carro/carro',{
        templateUrl:'view/criarAnuncio/veiculo/carro.html',
        controller:'carroController'
    }).when('/anuncio/veiculo/moto/moto',{
        templateUrl:'view/criarAnuncio/veiculo/moto.html',
        controller:'motoController'
    }).when('/anuncio/veiculo/barco/barco',{
        templateUrl:'view/criarAnuncio/veiculo/barco.html',
        controller:'barcoController'
    }).when('/anuncio/veiculo/caminhao/caminhao',{
        templateUrl:'view/criarAnuncio/veiculo/caminhao.html',
        controller:'caminhaoController'
    }).when('/anuncio/veiculo/agricola/agricola',{
        templateUrl:'view/criarAnuncio/veiculo/agricola.html',
        controller:'agricolaController'
    }).when('/anuncio/veiculo/esporte/esporte',{
        templateUrl:'view/criarAnuncio/veiculo/esporte.html',
        controller:'esporteController'
    }).when('/anuncio/veiculo/peca/peca',{
        templateUrl:'view/criarAnuncio/veiculo/peca.html',
        controller:'pecaController'
    }).when('/anuncio/outro',{
        templateUrl:'view/criarAnuncio/outros/outros.html',
        controller:'outrosController'
    }).when('/anuncio/mudanca/residencial/casa',{
        templateUrl:'view/criarAnuncio/mudanca/residencial.html',
        controller:'residencialController'
    }).when('/anuncio/mudanca/sobrado/sobrado',{
        templateUrl:'view/criarAnuncio/mudanca/sobrado.html',
        controller:'sobradoController'
    }).when('/anuncio/mudanca/apartamento/apartamento',{
        templateUrl:'view/criarAnuncio/mudanca/apartamento.html',
        controller:'apartamentoController'
    }).when('/anuncio/mudanca/comercial/comercio',{
        templateUrl:'view/criarAnuncio/mudanca/comercial.html',
        controller:'comercialController'
    }).when('/anuncio/mudanca/escritorio/escritorio',{
        templateUrl:'view/criarAnuncio/mudanca/escritorio.html',
        controller:'escritorioController'
    }).when('/anuncio/mudanca/industrial/industria',{
        templateUrl:'view/criarAnuncio/mudanca/industrial.html',
        controller:'industrialController'
    }).when('/anuncio/domestico/eletronico',{
        templateUrl:'view/criarAnuncio/domestico/domestico.html',
        controller:'domesticoController'
    }).when('/anuncio/telefonia/telefonia',{
        templateUrl:'view/criarAnuncio/domestico/telefonia.html',
        controller:'telefoniaController'
    }).when('/anuncio/animal/animal',{
        templateUrl:'view/criarAnuncio/domestico/animal.html',
        controller:'animalController'
    }).when('/anuncio/carga/carga_agricola',{
        templateUrl:'view/criarAnuncio/carga/carga.html',
        controller:'cargaController'
    }).when('/anuncio/carga/fracionada/carga_fracionada',{
        templateUrl:'view/criarAnuncio/carga/fracionada.html',
        controller:'fracionadaController'
    }).when('/anuncio/carga/completa/carga_completa',{
        templateUrl:'view/criarAnuncio/carga/completa.html',
        controller:'completaController'
    }).when('/anuncio/carga/fragil/carga_fragil',{
        templateUrl:'view/criarAnuncio/carga/fragil.html',
        controller:'fragilController'
    }).when('/anuncio/carga/container/container',{
        templateUrl:'view/criarAnuncio/carga/container.html',
        controller:'containerController'
    }).when('/alterarSenha',{
        templateUrl:'../view/alterarSenha.html',
        controller:'alterarSenhaController'
	}).when('/alterarEmail',{
		templateUrl:'../view/alterarEmail.html',
		controller:'alterarEmailController'
	}).when('/anuncios/:categoria',{
		templateUrl:'../view/anuncios-pesquisa.html',
		controller:'anunciosPesquisaController'
	}).when('/usuarios',{
		templateUrl:'../view/usuarios.html',
		controller:'usuariosListaController'
	}).when('/usuario/certificado',{
		templateUrl:'../view/certificado.html',
		controller:'certificadoController'
	}).when('/usuario/certificar',{
		templateUrl:'../view/certificar.html',
		controller:'certificarController'
	}).when('/alterarEmail/:token',{
		templateUrl:'../view/alterarEmail.html',
		controller:'alterarEmailController'
	}).when('/anuncios/buscar/:query',{
		templateUrl:'../view/anuncios-pesquisa.html',
		controller:'anunciosPesquisaController'
	}).when('/privacidade',{
		templateUrl:'../view/privacidade.html',
		controller:'privacidadeController'
	}).when('/usuario/acessar-perfil/:id',{
		templateUrl:'view/acessarPerfil.html',
		controller:'acessarPerfilController'
	}).when('/anuncio-detalhe/:idAnuncio',{
        templateUrl:'../view/anuncioDetalhe.html',
        controller:'anuncioDetalheController'
    }).when('/avaliarUsuario/:tipo/:id',{
		templateUrl:'../view/avaliarUsuario.html',
		controller:'avaliarUsuarioController'
	}).otherwise({
		redirectTo:'/'
	})
})
